1.

SELECT f.FL_FLIGHT_NO, f.FL_ORIG, f.FL_DEST, a.AIR_HUB_AIRLINE
FROM flight f
JOIN airport a ON f.FL_ORIG = a.AIR_CODE
WHERE a.AIR_HUB_AIRLINE = 'American' OR a.AIR_HUB_AIRLINE IS NULL
ORDER BY f.FL_FLIGHT_NO;

2.

SELECT f.FL_FLIGHT_NO, f.FL_ORIG, f.FL_DEST, a.AIR_HUB_AIRLINE
FROM flight f
JOIN airport a ON f.FL_ORIG = a.AIR_CODE
WHERE a.AIR_HUB_AIRLINE IS NULL
UNION
SELECT f.FL_FLIGHT_NO, f.FL_ORIG, f.FL_DEST, a.AIR_HUB_AIRLINE
FROM flight f
JOIN airport a ON f.FL_ORIG = a.AIR_CODE
WHERE a.AIR_HUB_AIRLINE = 'American'
ORDER BY FL_FLIGHT_NO;

3.

SELECT d.DEP_FLIGHT_NO, d.DEP_DEP_DATE, e.EQ_EQUIP_TYPE
FROM departures d
JOIN equip_type e ON d.DEP_EQUIP_NO = e.EQ_EQUIP_NO
WHERE e.EQ_EQUIP_TYPE = 'CONCORDE'
ORDER BY d.DEP_DEP_DATE, d.DEP_FLIGHT_NO;

4.

SELECT PIL_PILOT_ID, PIL_PILOTNAME
FROM pilots
MINUS
SELECT DEP_PILOT_ID, PIL_PILOTNAME
FROM departures
JOIN pilots ON DEP_PILOT_ID = PIL_PILOT_ID;

5.

SELECT PIL_PILOT_ID, PIL_PILOTNAME
FROM pilots
WHERE PIL_PILOT_ID NOT IN (SELECT DEP_PILOT_ID FROM departures)
ORDER BY PIL_PILOT_ID;

6.

SELECT p.PIL_PILOT_ID, p.PIL_PILOTNAME
FROM pilots p
LEFT JOIN departures d
ON p.PIL_PILOT_ID = d.DEP_PILOT_ID
WHERE d.DEP_PILOT_ID IS NULL
ORDER BY p.PIL_PILOT_ID;

7.

SELECT p.PAS_NAME,t.TIC_SEAT AS "Seat Number"
FROM passenger p
JOIN ticket t ON t.TIC_ITINERARY_NO = p.PAS_ITINERARY_NO
WHERE t.TIC_FLIGHT_NO = '101' AND t.TIC_FLIGHT_DATE = '15-JUL-17'
ORDER BY PAS_NAME

8.

SELECT DEP_FLIGHT_NO AS "Flight Number", DEP_DEP_DATE  AS "Date",COUNT(*) AS "Number of Passengers"
from departures d
JOIN ticket t ON t.TIC_FLIGHT_NO = d.DEP_FLIGHT_NO
JOIN passenger p ON p.PAS_ITINERARY_NO = t.TIC_ITINERARY_NO
GROUP BY DEP_FLIGHT_NO, DEP_DEP_DATE
HAVING COUNT(*) > 5;

9.

SELECT f.FL_FLIGHT_NO, f.FL_ORIG, f.FL_DEST 
FROM flight f
JOIN reservation r ON r.RES_FLIGHT_NO = f.FL_FLIGHT_NO
WHERE r.RES_NAME = 'Andy Anderson'
ORDER BY f.FL_FLIGHT_NO

10.

SELECT a1.AIR_LOCATION AS "Departs From", a2.AIR_LOCATION AS "Arrives at", MIN(FL_FARE) AS "Minimum Fare"
FROM flight
JOIN airport a1 ON flight.FL_ORIG = a1.AIR_CODE
JOIN airport a2 ON flight.FL_DEST = a2.AIR_CODE
GROUP BY a1.AIR_LOCATION, a2.AIR_LOCATION
