SELECT PAS_NAME, PAS_ITINERARY_NO, PAS_FARE, PAS_CONFIRM_NO 
FROM passenger 
ORDER BY PAS_NAME, PAS_FARE;

SELECT PIL_PILOTNAME, PIL_STATE, PIL_ZIP, PIL_FLIGHT_PAY
FROM pilots
WHERE (PIL_STATE = 'TX' OR PIL_STATE = 'AZ') AND PIL_FLIGHT_PAY > 2500
ORDER BY PIL_FLIGHT_PAY DESC;

SELECT PIL_PILOTNAME, PIL_ZIP, PIL_FLIGHT_PAY
FROM pilots
WHERE PIL_STATE IN ('TX', 'AZ') AND PIL_FLIGHT_PAY > 2500
ORDER BY PIL_FLIGHT_PAY DESC;

SELECT PIL_PILOTNAME, PIL_ZIP, PIL_FLIGHT_PAY
FROM pilots
WHERE PIL_FLIGHT_PAY > 2500 AND PIL_STATE = 'TX'
UNION
SELECT PIL_PILOTNAME, PIL_ZIP, PIL_FLIGHT_PAY
FROM pilots
WHERE PIL_FLIGHT_PAY > 2500 AND PIL_STATE = 'AZ'
ORDER BY PIL_FLIGHT_PAY DESC;

SELECT EQ_EQUIP_NO, EQ_EQUIP_TYPE, EQ_SEAT_CAPACITY, EQ_FUEL_CAPACITY, EQ_MILES_PER_GAL 
FROM EQUIP_TYPE 
WHERE EQ_SEAT_CAPACITY > 300 OR (EQ_MILES_PER_GAL > 3.5 AND EQ_FUEL_CAPACITY < 2500) 
ORDER BY EQ_EQUIP_NO;


SELECT EQ_EQUIP_NO, EQ_EQUIP_TYPE, EQ_SEAT_CAPACITY, EQ_FUEL_CAPACITY, EQ_MILES_PER_GAL
FROM EQUIP_TYPE 
WHERE EQ_SEAT_CAPACITY > 300
UNION
SELECT EQ_EQUIP_NO, EQ_EQUIP_TYPE, EQ_SEAT_CAPACITY, EQ_FUEL_CAPACITY, EQ_MILES_PER_GAL
FROM EQUIP_TYPE 
WHERE EQ_MILES_PER_GAL > 3.5 AND EQ_FUEL_CAPACITY < 2500
ORDER BY EQ_EQUIP_NO;


SELECT * FROM airport WHERE AIR_LOCATION LIKE '%TX';


SELECT DEP_PILOT_ID, COUNT(*) AS "Flights"
FROM DEPARTURES
GROUP BY DEP_PILOT_ID
HAVING COUNT(*) > 20
ORDER BY "DEP_PILOT_ID" ASC;

SELECT FL_FLIGHT_NO AS "Flight Number", FL_FARE AS "Fare", FL_DISTANCE AS "Distance", 
       ROUND((FL_DISTANCE/FL_FARE), 2) AS "Miles Flown Per Dollar"
FROM flight
WHERE (FL_DISTANCE/FL_FARE) > 5.50
ORDER BY "Miles Flown Per Dollar" DESC;



SELECT a.AIR_LOCATION AS "Airport Location", COUNT(*) AS "Number of Departing Flights"
FROM flight f
JOIN airport a ON f.FL_ORIG = a.AIR_CODE
GROUP BY a.AIR_LOCATION;


SELECT PIL_STATE AS "State", 
       MAX(PIL_FLIGHT_PAY) AS "Max Pay", 
       MIN(PIL_FLIGHT_PAY) AS "Min Pay", 
       AVG(PIL_FLIGHT_PAY) AS "Avg Pay"
FROM pilots
GROUP BY PIL_STATE;


SELECT PIL_PILOTNAME AS "Pilot Name", MIN(DEP_DEP_DATE) AS "First Departure Date"
FROM pilots
JOIN departures ON PIL_PILOT_ID = DEP_PILOT_ID
GROUP BY PIL_PILOTNAME
ORDER BY PIL_PILOTNAME;

SELECT eq.EQ_EQUIP_TYPE AS "Equipment Type", MAX(eq.EQ_FUEL_CAPACITY* eq.EQ_MILES_PER_GAL) AS "Maximum Distance Flown"
FROM flight f
JOIN departures d ON f.FL_FLIGHT_NO = d.DEP_FLIGHT_NO
JOIN equip_type eq ON d.DEP_EQUIP_NO = eq.EQ_EQUIP_NO
GROUP BY eq.EQ_EQUIP_TYPE
ORDER BY "Maximum Distance Flown" DESC;


SELECT FL_ORIG AS "Airport Code", COUNT(*) AS "NUMBER_OF_FLIGHTS"
FROM flight
GROUP BY FL_ORIG


SELECT eq.EQ_EQUIP_TYPE AS "Equipment Type", MAX(eq.EQ_FUEL_CAPACITY * eq.EQ_MILES_PER_GAL) AS "Maximum Distance Flown"
FROM flight f
JOIN departures d ON f.FL_FLIGHT_NO = d.DEP_FLIGHT_NO
JOIN equip_type eq ON d.DEP_EQUIP_NO = eq.EQ_EQUIP_NO
GROUP BY eq.EQ_EQUIP_TYPE
HAVING MAX(eq.EQ_FUEL_CAPACITY * eq.EQ_MILES_PER_GAL) > 8600
ORDER BY "Maximum Distance Flown" ASC;

